import content from '../../src/data/content.json';
import { menuTree } from './legacy';

function FooterMenu({ title, items }) {
  return <div className="col-xs-24 col-sm-12 col-md-6"><h3>{title}</h3><ul className="menu">{items.map((item) => <li key={item.id}><a href={item.href}>{item.title}</a></li>)}</ul></div>;
}

export default function Footer() {
  const regulations = menuTree(3);
  return <><footer id="footer"><div className="wraper"><div className="container"><div className="row"><div className="col-xs-24 col-sm-12 col-md-6"><h3>Trực thuộc</h3><ul className="company_info"><li>Địa chỉ: Số 74 Nguyễn Lân, Phương Liệt, Thanh Xuân, Hà Nội</li><li>Điện thoại: Hỗ trợ - Khiếu nại: <a href="tel:0903419596">090 341 9596</a></li><li>Skype: <a href="skype:inansangtao.com">inansangtao.com</a></li><li>Email: <a href="mailto:inansangtao.com@gmail.com">inansangtao.com@gmail.com</a></li></ul></div><div className="col-xs-24 col-sm-12 col-md-6"><h3>Đăng kí nhận tin</h3><form className="newsnotice" action="#"><div className="input-group"><input type="email" className="form-control" placeholder="Email của bạn" aria-label="Email của bạn" /><span className="input-group-btn"><button className="btn btn-info" type="button">Gửi</button></span></div></form><h3>Liên hệ</h3><ul className="menu"><li>CÔNG TY CỔ PHẦN PHÁT TRIỂN THƯƠNG HIỆU HOÀNG GIA</li><li>Kinh doanh 1: <a href="tel:0911424420">0911424420</a></li><li>Email: <a href="mailto:baogia.inansangtao@gmail.com">baogia.inansangtao@gmail.com</a></li><li>Kinh doanh 2: <a href="tel:0911618185">0911618185</a></li><li>Email: <a href="mailto:baogia.inansangtao@gmail.com">baogia.inansangtao@gmail.com</a></li><li>Design: <a href="mailto:thietke.inansangtao@gmail.com">thietke.inansangtao@gmail.com</a></li><li>CN Miền Bắc: Số 74 Nguyễn Lân, Thanh Xuân, Hà Nội.</li><li>CN Miền Trung: K53/2 đường 2/9 quận Hải Châu, Tp. Đà Nẵng</li><li>CN Miền Nam: 285/94 đường Cách Mạng Tháng 8, Phường 12, Quận 10, Tp. Hồ Chí Minh</li></ul></div><FooterMenu title="Quy định chung" items={regulations} /><div className="col-xs-24 col-sm-12 col-md-6"><h3>Mạng xã hội</h3><p><a href="https://facebook.com/Inansangtao.Com.0903419596/" target="_blank" rel="noreferrer">Theo dõi In Ấn Sáng Tạo trên Facebook</a></p><a href="/"><img src="/uploads/asset-1_1.png" alt="In Ấn Sáng Tạo" width="260" height="36" /></a></div></div></div></div></footer><nav className="footerNav2"><div className="wraper"><div className="container"><div className="copyright">© Bản quyền thuộc về <a href="/">Công ty cổ phần phát triển thương hiệu Hoàng Gia</a>.</div></div></div></nav><div className="social-button"><div className="social-button-content"><a href="tel:0911618185" className="call-icon" rel="nofollow"><i className="fa fa-phone" /><span>Hotline: 0911 618 185</span></a><a href="https://zalo.me/0911618185" className="zalo" target="_blank" rel="noreferrer"><i className="fa fa-commenting-o" /><span>Zalo: 0911 618 185</span></a></div></div></>;
}
