import content from '../../src/data/content.json';
import { menuTree } from './legacy';

function MenuItems({ items }) {
  return items.map((item) => <li key={item.id} className={`${item.children.length ? 'dropdown ' : ''}${item.icon || ''}`}><a href={item.href} target={item.target} rel={item.target === '_blank' ? 'noreferrer' : undefined}>{item.title}{item.children.length > 0 && <span className="caret" />}</a>{item.children.length > 0 && <ul className="dropdown-menu"><MenuItems items={item.children} /></ul>}</li>);
}

export default function Header() {
  const items = menuTree(1);
  const homeItem = { id: 'home', title: 'Trang chủ', href: '/', target: '_self', icon: '', children: [] };
  return <><header><div className="wraper"><div className="container"><div id="header" className="row"><div className="logo col-xs-16 col-sm-12 col-md-4"><a title={content.site.name} href="/"><img src={content.site.logo} alt={content.site.name} /></a></div><div className="col-xs-8 col-sm-24 col-md-18"><nav className="second-nav" id="menusite"><div className="navbar navbar-default"><ul className="nav navbar-nav"><MenuItems items={[homeItem, ...items]} /></ul></div></nav></div><div className="hidden-xs col-sm-24 col-md-4"><div className="headerSearch"><div className="input-group"><form action="/blog/" method="get"><input className="form-control" name="q" maxLength="100" placeholder="Tìm kiếm..." /><span className="input-group-btn"><button className="btn btn-info" aria-label="Tìm kiếm"><i className="fa fa-search fa-lg" /></button></span></form></div></div></div></div></div></div></header><nav className="header-nav"><div className="wraper"><div className="container"><div className="row"><div className="col-md-24"><div className="social-icons"><a href="https://facebook.com/Inansangtao.Com.0903419596/"><img src="/uploads/35.png" alt="Facebook" width="37" height="37" /></a><a href="https://plus.google.com/"><img src="/uploads/36.png" alt="Google+" width="37" height="37" /></a><a href="https://youtube.com/"><img src="/uploads/37_1.png" alt="Youtube" width="37" height="37" /></a></div><div className="contactDefault"><a href="tel:+84911424420">Hotline : &nbsp;0911 424 420</a><span>&nbsp; <i className="fa fa-envelope" /> </span><a href="mailto:inansangtao.com@gmail.com">inansangtao.com@gmail.com</a><span>&nbsp; <i className="fa fa-skype" /> </span><a href="skype:inansangtao">inansangtao</a></div></div></div></div></div></nav></>;
}
